apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v1
  labels:
    app: frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
      - name: frontend
        image: registry.gitlab.com/gihyo-ms-dev-book/handson/sec3/3.4-auth/frontend:v1
        ports:
        - containerPort: 80
